### PR TITLE
fix(UI): script to register at viewer has to require viewer

### PR DESCRIPTION
**Pull request by blizzz**
* Target version: main

### Summary

avoids conditions where registering is attempted when OCA.Viewer is not established yet

### Checklist

- [X] Code is properly formatted
- [X] Sign-off message is added to all commits
- [X] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by blizzz** [comment]
@juliushaertl we discussed the problem i was facing yesterday. with this change, i can open documents properly now on the dev setup.

**Review by juliushaertl — COMMENTED** [review]
We should probably rather make use of https://github.com/nextcloud/server/pull/30015 and add viewer as 3rd parameter to https://github.com/nextcloud/officeonline/blob/main/lib/Listener/LoadViewerListener.php#L13 so that the officeonline script is only loaded after viewer has been.

**Comment by blizzz** [comment]
> We should probably rather make use of [nextcloud/server#30015](https://github.com/nextcloud/server/pull/30015) and add viewer as 3rd parameter to https://github.com/nextcloud/officeonline/blob/main/lib/Listener/LoadViewerListener.php#L13 so that the officeonline script is only loaded after viewer has been.

Cool. Did not know we have that.

**Comment by blizzz** [comment]
Changed the PR accordingly.

**Pull request merged**
