### PR TITLE
Update Viewer to import ccs icons

### PR DESCRIPTION
**Pull request by andyxheli**
Signed-off-by: Andrea Xheli axheli@axtsolutions.com

* Resolves: (https://github.com/nextcloud/officeonline/issues/144
* Target version: master

### CODE REVIEW

**Comment by andyxheli** [comment]
@juliushaertl Please review :)

**Comment by juliushaertl** [comment]
Thanks a lot @andyxheli Seems just the filetypes.scss file is missing from the commit :wink:

**Comment by andyxheli** [comment]
You're Welcome! I create it in Add CSS file for icons #254 sorry new to this

**Comment by andyxheli** [comment]
Thank you for the feedback @juliushaertl :) Okay i just added the file to the PR I created a separate one but closed it.

**Comment by andyxheli** [comment]
Hey @juliushaertl Happy New Year! When you get some free time can you please review this :)

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
