### PR TITLE
Fix PDF Issue

### PR DESCRIPTION
**Pull request by andyxheli**
Signed-off-by: Andrea Xheli axheli@axtsolutions.com

* Resolves: PDF are opening under ms office #234
* Target version: master 

### Summary
Temp Fix

### Checklist

- [ ] Code is properly formatted
- [ ] Sign-off message is added to all commits
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by juliushaertl** [comment]
Thanks for your pull request, as just mentioned in the comments I think the optional mimetype handler would still make sense, it just needs to be ensured that the viewer integration is not taking that into account as currently not supported in the viewer:

https://github.com/nextcloud/officeonline/blob/master/src/viewer.js#L3

**Comment by andyxheli** [comment]
You're Welcome! Thank you for your response. Should it look something like this? 

image

**Comment by andyxheli** [comment]
Okay perfect! Thank you. So first revert this file and modify the viewer.js#L3

**Comment by andyxheli** [comment]
Just created a new pull request Update viewer.js #244

**Pull request closed without merging**
